### ISSUE TITLE
Functionality for working with subnet attributes of storage nodes

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-sdk-go#82]
Blocked by:

- https://github.com/nspcc-dev/neofs-sdk-go/issues/79
- https://github.com/nspcc-dev/neofs-api-go/issues/356

## Summary
We need to provide a convenient platform for storage nodes to participate in subnets. It should should subnet ID and be based on node attributes.

## Task

- [ ] Add `func netmap.AddSubnet(*NodeInfo, subnet.ID)` which adds subnet attribute if it doesn't exist.
- [ ] Add `func netmap.DropSubnet(*NodeInfo, subnet.ID)` which drops subnet attribute if it exists.
- [ ] Add `func netmap.IterateSubnets(*NodeInfo, func(subnet.ID) error` which iterates over all subnets. Returns error if at least one subnet attribute is invalid. Forwards handler's error, except `ErrDrop` - in this case current attributed is dropped and iterating continues.
